apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
{{- template "mychart.systemlabels" $ }}
{{ include "mychart.version" . | indent 4 }}
data:
  myvalue: "Sample Config Map"
  costCode: {{ .Values.costCode }}
  Zone: {{ quote .Values.infra.zone }}
  Region: {{ quote .Values.infra.region }}
  ProjectCode: {{ upper .Values.projectCode }}
  orgdomain: {{ .Values.global.orgdomain }}
